"""add gap_dismissed to messages

Revision ID: 4ced1fc7b5d3
Revises: f98bc802920b
Create Date: 2026-09-10 11:30:28.487199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ced1fc7b5d3'
down_revision: Union[str, None] = 'f98bc802920b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'messages',
        sa.Column('gap_dismissed', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'gap_dismissed')
    # ### end Alembic commands ###
