"""add trigram index for korean text search

Revision ID: f98bc802920b
Revises: e63b1aff60c6
Create Date: 2026-09-10 10:03:09.056137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98bc802920b'
down_revision: Union[str, None] = 'e63b1aff60c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_knowledge_chunks_content_trgm', 'knowledge_chunks', ['content'], unique=False, postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_chunks_content_trgm', table_name='knowledge_chunks', postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    # ### end Alembic commands ###
